name: Nginx Restore

on:
  workflow_call:
    inputs:
      backup_dir:
        type: string
        default: "${{ vars.NGINX_BAK_PATH }}"

jobs:
  restore:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout DevOpsTemplates
        uses: actions/checkout@v4
        with:
          repository: leoserverteam/DevOpsTemplates
          path: templates

      - name: Run Restore Script
        env:
          # Прокидываем переменные организации и инпуты в окружение
          NGINX_PATH: ${{ vars.NGINX_PATH }}
          BACKUP_DIR: ${{ inputs.backup_dir }}
        run: |
          python3 templates/restorenginx.py
