name: Reusable Docker Deploy

on:
  workflow_call:
    # Оставляем inputs, если захотим уточнить подпапку для конкретного проекта
    inputs:
      project_name:
        required: true
        type: string
      extra_files:
        required: false
        type: string
        default: ""

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Organization Path
        run: |
          TARGET_DIR="${{ vars.DEPLOY_PATH }}/${{ inputs.project_name }}"
          mkdir -p "$TARGET_DIR"
          
          # 1. Всегда копируем основной файл
          cp docker-compose.yml "$TARGET_DIR/"
          
          # 2. Копируем дополнительные файлы/папки, если они указаны
          EXTRA_FILES="${{ inputs.extra_files }}"
          if [ -n "$EXTRA_FILES" ]; then
            for ITEM in $EXTRA_FILES; do
              echo "Copying $ITEM to $TARGET_DIR..."
              # Используем cp -r для поддержки папок
              cp -r "$ITEM" "$TARGET_DIR/"
            done
          fi
          
          cd "$TARGET_DIR"
          docker-compose pull
          docker-compose up -d --remove-orphans
